### ISSUE TITLE
add command for extending the expiration date of a cluster

### ISSUE THREAD

**Issue by jbpratt** [ryankwilliams/ocm-toolbox#1]
Having a command to easily extend the expiration date of a cluster would be convenient :cat: 

`extend-expiration --cluster-id <CLUSTER_ID> 2h`
`extend-expiration --cluster-id <CLUSTER_ID> 1d`
`extend-expiration --cluster-id <CLUSTER_ID> 20m`

**Comment by ryankwilliams** [comment]
@jbpratt PR opened for this, let me know if this works!
